### ISSUE TITLE
QR Code data

### ISSUE THREAD

**Issue by Sikerdebaard** [minvws/nl-covid19-coronacheck-mobile-core#1]
Hi,

Ik ben erg geïntresseerd in het uitlezen van de data die in de nationale vaccinatie QR code staat. Die lijkt anders in elkaar te zitten dan de EHC (Europese) QR code. De Android en iOS apps lijken deze code te genereren en decoderen met behulp van een mobilecore library geschreven in Golang. Is dit de repo voor deze library? Komt deze library op termijn beschikbaar voor het publiek? En hoe lezen wij de blob in de QR code uit?

**Comment by readefries** [comment]
Wat ik gelezen heb, is dat voor de NL QR code ASN.1 gebruikt wordt. Ik kan helaas nog niet inloggen om te kijken hoe het eruit ziet.

**Comment by confiks** [comment]
Hallo! Ik heb de code net op de publieke repo's gepushed. Je zal in deze repository event `.gitmodule` moeten aanpassen om de `-private` suffix te verwijderen. Als je het pad langs het CLI command `euqr` volgt (die ondanks de naam ook Nederlandse privacy-vriendelijke QR codes kan verifiëren) kom je bij de serialization en verification-code uit in `coronacheck-idemix`.

Binnenkort meer info in de README hier. Zie alvast [dit document](https://github.com/minvws/nl-covid19-coronacheck-app-coordination-private/blob/feature/stripcard/architecture/Privacy%20Preserving%20Green%20Card.md) voor de insteek, en de [IRMA documentatie](https://irma.app/docs/zkp/) voor cryptografische achtergrond (de cryptografisch kern van IRMA wordt gebruikt).

Let wel op [artikel 58re lid 3 Wpb](https://wetten.overheid.nl/jci1.3:c:BWBR0024705&hoofdstuk=Va&paragraaf=3a&artikel=58re&z=2021-06-24&g=2021-06-24), "voor het lezen van het elektronisch of schriftelijk coronatoegangsbewijs wordt een door Onze Minister beschikbaar gestelde applicatie gebruikt".

**Comment by Sikerdebaard** [comment]
Top dankjewel!

**Comment by Sikerdebaard** [comment]
Hmm ik loop tegen een probleem aan. De Base45 decoder die jullie gebruiken, volgt die deze draft net zoals de europese QR code? https://datatracker.ietf.org/doc/draft-faltstrom-base45/

Dat er een domestic base45 decoder is en een eubase45 doet mij vermoeden dat die net wat anders werken. Of dat ik een stap mis tussen het base45 gedeelte en het ASN.1 gedeelte.

**Comment by confiks** [comment]
Klopt. De Europese variant kan beter 'base41 met base45' charset heten. We hadden de efficiency van echte base45 echt nodig voor deze (grote) QR codes, dus ik heb ook base45 geïmplementeerd die gelijk is aan base58 (maar met de QR charset). 

Repo is public, maar moet nog verhuisd worden (zie de `replace` regel in `go.mod`): https://github.com/confiks/base45-go

**Comment by Sikerdebaard** [comment]
Ah ik ben niet zo bekend met GoLang dus ik had dit over het hoofd gezien. :)

Dank voor de code!
